[package]
name = "samba_cargo"
version = "0.1.0"
edition = "2024"

[[bin]]
# This can be whatever name makes sense for your project, but the rest of this tutorial assumes uniffi-bindgen.
name = "uniffi-bindgen"
path = "uniffi_bindgen.rs"

[lib]
name = "samba_cargo"
crate-type = ["cdylib", "staticlib"]
path = "src/commonMain/rust/lib.rs"

[dependencies]
uniffi = { version = "0.32.0", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.32.0", features = ["build"] }