---
config:
  theme: neo-dark
  layout: elk
---
classDiagram

%% @Serializable
%% @Polymorphic
class MyPath {
    << interface >>
    val rawPath: String
    override fun toString(): String = rawPath

    suspend fun stat(): FileMetadata?

    suspend fun name(): String?
    suspend fun metadata(): FileMetadata?
    suspend fun toMyDirectory(): MyDirectory?
    suspend fun toMyFile(): MyFile?

    suspend fun mv(destination: MyPath): MyPath
    suspend fun cp(destination: MyPath): MyPath
    suspend fun mk(): MyPath
    suspend fun rm()
}

MyPath <|-- MyFile
%% @Serializable
class MyFile {
    << interface >>
    override suspend fun toMyDirectory(): MyDirectory? = null
    override suspend fun toMyFile(): MyFile? = this

    suspend fun source(): RawSource
    suspend fun sink(append: Boolean = false): RawSink

    suspend fun <T> read(serializer: KSerializer<T>, format: StringFormat = JsonDefault): T
        %% = withContext(Dispatchers.IO) { when(format) {
        %%     is Json -> source().buffered().use { format.decodeFromSource(serializer, it) }
        %%     else -> format.decodeFromString(serializer, read())
        %% }}
    suspend fun readByteArray(): ByteArray
        %% = withContext(Dispatchers.IO) { source().buffered().use { it.readByteArray() } }
    suspend fun <T> readFromBinary(serializer: KSerializer<T>, format: BinaryFormat = Cbor): T
        %% = withContext(Dispatchers.IO) { format.decodeFromByteArray(serializer, readByteArray()) }
    suspend fun readString(): String
        %% = withContext(Dispatchers.IO) { source().buffered().use { it.read() } }
    
    suspend fun <T> write(value: T, serializer: KSerializer<T>, format: StringFormat = JsonDefault): MyFile
        %% = withContext(Dispatchers.IO) { when(format) {
        %%     is Json -> sink(false).buffered().use { format.encodeToSink(serializer, value, it) }
        %%     else -> writeString(format.encodeToString(serializer, value), false)
        %% }}
    suspend fun writeByteArray(value: ByteArray, append: Boolean = false): MyFile
        %% = withContext(Dispatchers.IO) { sink(append).buffered().use { it.write(value) } }
    suspend fun writeString(value: String, append: Boolean = false): MyFile
        %% = withContext(Dispatchers.IO) { sink(append).buffered().use { it.writeString(value) } }
    suspend fun <T> writeToBinary(value: T, serializer: KSerializer<T>, format: BinaryFormat = Cbor): MyFile
        %% = withContext(Dispatchers.IO) { writeByteArray(format.encodeToByteArray(serializer, value), false) }
}

MyPath <|-- MyDirectory
%% @Serializable
class MyDirectory {
    << interface >>
    override suspend fun toMyDirectory(): MyDirectory? = this
    override suspend fun toMyFile(): MyFile? = null

    suspend fun list(pattern: Regex? = null): Sequence<MyPath>
    suspend fun mkdirs(): MyDirectory
}
    

MyPath <|-- LocalPath
%% @Serializable
%% @SerialName("LocalPath")
class LocalPath {
    << expect open >>
    constructor(
        override val rawPath: String
        @Transient val path: Path = Path(rawPath.stripPrefix())
        @Transient private var metadata_: FileMetadata? = null
    )

    override suspend fun stat(): FileMetadata?
        %% = withContext(Dispatchers.IO) { 
        %%     SystemFileSystem.metadataOrNull(path).also { metadata_ = it } 
        %% }

    override suspend fun name(): String?
        %% = path.name
    override suspend fun metadata(): FileMetadata?
        %% = metadata_ ?: stat()
    override open suspend fun toMyDirectory(): MyDirectory?
        %% = if(metadata()?.isDirectory ?: false) LocalDirectory(this) else null
    override open suspend fun toMyFile(): MyFile?
        %% = if(metadata()?.isRegularFile ?: false) LocalFile(this) else null

    override suspend fun mv(destination: MyPath): MyPath
        %% = apply { withContext(Dispatchers.IO) { SystemFileSystem.atomicMove(path, destination) } }
}


LocalPath <|-- LocalFile
MyFile <|-- LocalFile
%% @Serializable
%% @SerialName("LocalFile")
class LocalFile {
    override suspend fun toMyFile(): MyFile? = this
    override suspend fun toMyDirectory(): MyDirectory? = null

    override suspend fun source(): RawSource
        %% = withContext(Dispatchers.IO) { SystemFileSystem.source(path) }
    override suspend fun sink(append: Boolean = false): RawSink
        %% = withContext(Dispatchers.IO) { SystemFileSystem.sink(path) }

    override suspend fun cp(destination: MyPath): MyPath
        %% = apply {
        %%     require(destination is MyFile)
        %%     destination.writeByteArray(readByteArray())        %% }
    override suspend fun mk(): MyPath
        %% = apply { withContext(Dispatchers.IO) { writeString("") } }
    override suspend fun rm()
        %% = withContext(Dispatchers.IO) { SystemFileSystem.delete(path) } }
}


LocalPath <|-- LocalDirectory
MyDirectory <|-- LocalDirectory
%% @Serializable
%% @SerialName("LocalDirectory")
class LocalDirectory {
    override suspend fun toMyDirectory(): MyDirectory? = this
    override suspend fun toMyFile(): MyFile? = null

    override suspend fun cp(destination: MyPath): MyPath
    override suspend fun mk(): MyPath
    override suspend fun rm()

    override suspend fun list(pattern: Regex? = null): Sequence<MyPath>
    override suspend fun mkdirs(): MyDirectory
        %% = apply { withContext(Dispatchers.IO) { 
        %%     SystemFileSystem createDirectories(path) 
        %% }}
}

%% val LocalFsModule = SerializersModule {
%%     polymorphic(MyPath::class) {
%%         subclass(LocalPath::class)
%%         subclass(LocalFile::class)
%%         subclass(LocalDirectory::class)
%%     }
%% }


class SmbPath {
    << open >>
    isOK() bool
  }
class SmbFile
class SmbDirectory
%% val SmbFsModule = SerializersModule {
%%     polymorphic(MyPath::class) {
%%         subclass(SmbPath::class)
%%         subclass(SmbFile::class)
%%         subclass(SmbDirectory::class)
%%     }
%% }



  %% ===========================
  %% URI (Android SAF)
  %% ===========================
  namespace android {
    class URIPath {
      << open >>
      android.net.Uri path
    }
    class URIFile
    class URIDirectory
  }
  
  URIPath <|-- URIFile
  URIPath <|-- URIDirectory

  %% ===========================
  %% Asset (read-only)
  %% ===========================
  class AssetPath { << open >> }
  class AssetFile
  class AssetDirectory

  AssetPath <|-- AssetFile
  AssetPath <|-- AssetDirectory

  %% ===========================
  %% Zip (Rust)
  %% ===========================
  class ZipPath {
    << open >>
    long? uncompressedSize
  }
  class ZipFile
  class ZipDirectory

  ZipPath <|-- ZipFile
  ZipPath <|-- ZipDirectory


  %% ===========================
  %% HTTP
  %% ===========================
  class HttpPath { << open >> }
  class HttpFile

  HttpPath <|-- HttpFile

  %% ===========================
  %% Temp
  %% ===========================
  class TempPath { << open >> }
  class TempFile
  class TempDirectory

  TempPath <|-- TempFile
  TempPath <|-- TempDirectory


  %% ===========================
  %% Google Drive
  %% ===========================
  class GoogleDrivePath { << open >> }
  class GoogleDriveFile
  class GoogleDriveDirectory

  GoogleDrivePath <|-- GoogleDriveFile
  GoogleDrivePath <|-- GoogleDriveDirectory
